targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          generic_argument_factories: true
          field_rename: "snake"
        
     