name: mews_moviedb_exercise
description: Mews Movie Database Exercise

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  bloc_test: ^9.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  dio_http_formatter: ^2.1.0
  duration: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mocktail: ^0.2.0
  palette_generator: ^0.3.2
  provider: ^6.0.2
  retrofit: ^3.0.1
  rive: ^0.8.1
  rxdart: ^0.27.3
  sliver_tools: ^0.2.5

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_gen_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1

dependency_overrides:
  test_api: 0.4.9

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    rive: true
    flutter_svg: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/svg/
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
